### ISSUE TITLE
Move the asterisks to the end of the field name

### ISSUE THREAD

**Issue by oeway** [14nrv/vue-form-json#60]
Hi, I got some feedback from some users, suggesting that the asterisks is a bit confusing. 
<img width="1093" alt="Screen Shot 2021-07-08 at 8 25 14 PM" src="https://user-images.githubusercontent.com/478667/124972435-a49e0600-e02a-11eb-90f6-8a62dbc17f00.png">

And I think it would be indeed nicer if we move the asterisks to the end of the field name (instead of the end of the explanatory sentence).

**Comment by 14nrv** [comment]
Hi, I think it s confusing because the sentences are very long and not inside parenthesis compare to the CodeSandbox example:
<img width="480" alt="Capture d’écran 2021-07-08 à 20 42 04" src="https://user-images.githubusercontent.com/34603467/124974361-fe073480-e02c-11eb-9fff-f8d48b03e06b.png">

Perhaps you could simply "cheat", one more time, with the famous `html` :)
Adding a new props to this project, like `hasAsteriskJustAfterLabel` could be also an option.

**Comment by oeway** [comment]
> Perhaps you could simply "cheat", one more time, with the famous html :)
Adding a new props to this project, like hasAsteriskJustAfterLabel could be also an option.

Right, but that's a bit hacky way of doing stuff, it doesn't feel right to have lots of html code embedded in js code. If possible, could you please have that implemented here? Either change it directly, or as an option.

**Comment by 14nrv** [comment]
What do you think of adding a new props `hasAsteriskJustAfterLabel` like [the other one](https://github.com/14nrv/vue-form-json#props-available-on-formjson-component) that will be applied globally? The default value will be `false`.

**Comment by oeway** [comment]
> the other one

Yes, that would work!

For custom field components (`is: Component`), can we also read these options somewhere?

**Comment by 14nrv** [comment]
> For custom field components (is: Component), can we also read these options somewhere?

I think yes because it s passed to the props `formFields`

**Comment by oeway** [comment]
thank you！
